db: biu
server:
  port: 8888
  servlet:
    context-path: /api/v1
spring:
  profiles:
    active: dev
    include: druid,mybatisplus
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${db}?characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
logging:
  level:
    com.abc.dao: debug
  path: ./logs